// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkBFVDWG0o97uYVh-5aux63_DG9Nqe9gA',
    appId: '1:673521878608:web:b5a00810382934ec20f355',
    messagingSenderId: '673521878608',
    projectId: 'yaksok-6f58b',
    authDomain: 'yaksok-6f58b.firebaseapp.com',
    storageBucket: 'yaksok-6f58b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwH0WeWMGa_Si7VEA0dUZGTYnyLDNdTMo',
    appId: '1:673521878608:android:9bd1ed6bb9c318cf20f355',
    messagingSenderId: '673521878608',
    projectId: 'yaksok-6f58b',
    storageBucket: 'yaksok-6f58b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIiIWsDB5oi6ozdBucmIV0A5QsK7uhn-k',
    appId: '1:673521878608:ios:d3710af96a3a769f20f355',
    messagingSenderId: '673521878608',
    projectId: 'yaksok-6f58b',
    storageBucket: 'yaksok-6f58b.firebasestorage.app',
    iosBundleId: 'com.example.yaksok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIiIWsDB5oi6ozdBucmIV0A5QsK7uhn-k',
    appId: '1:673521878608:ios:d3710af96a3a769f20f355',
    messagingSenderId: '673521878608',
    projectId: 'yaksok-6f58b',
    storageBucket: 'yaksok-6f58b.firebasestorage.app',
    iosBundleId: 'com.example.yaksok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkBFVDWG0o97uYVh-5aux63_DG9Nqe9gA',
    appId: '1:673521878608:web:ef474d171474d40220f355',
    messagingSenderId: '673521878608',
    projectId: 'yaksok-6f58b',
    authDomain: 'yaksok-6f58b.firebaseapp.com',
    storageBucket: 'yaksok-6f58b.firebasestorage.app',
  );
}
